Create TopicsViewModel
Juancaceres963/ReactApp.Net pull request #11
Opened 2024-11-05 00:06 UTC by Juancaceres963

2024-11-05 00:51 UTC, jaco9419 commented
Va perfecto hasta acá.

2024-11-06 16:55 UTC, jaco9419 requested changes

2024-11-06 16:55 UTC, jaco9419 commented on AndreinaArtistica/Resources/Helpers/DatabaseHelper.cs
> +        }
Change all that says `public` to change to `public static`

2024-11-06 16:55 UTC, jaco9419 commented on AndreinaArtistica/Resources/ArtPiecesResource.cs
> +        private readonly DatabaseHelper _databaseHelper;
Remove this

2024-11-06 16:55 UTC, jaco9419 commented on AndreinaArtistica/Resources/ArtPiecesResource.cs
> +            var techniquesList = await _databaseHelper.GetTechniquesFromDB();
Change to
```
            var categoriesList = await DatabaseHelper.GetCategoriesFromDB();
            var materialsList = await DatabaseHelper.GetMaterialsFromDB();
            var topicsList = await DatabaseHelper.GetTopicsFromDB();
            var techniquesList = await DatabaseHelper.GetTechniquesFromDB();
```

2024-11-06 16:55 UTC, jaco9419 commented on AndreinaArtistica/Resources/TopicsResource.cs
> +        }
Ya tienes este método en `DatabaseHelper` así que puedes hacer algo parecido a como estás trayendo los topics en `ArtPiecesResource.cs` luego de los cambios que propuse.

2024-11-06 17:09 UTC, jaco9419 commented on AndreinaArtistica/Resources/Helpers/DatabaseHelper.cs
> +        }
Este creo que no hace falta cambiar. Prueba a ver, capaz te da error si lo cambias.
```
public DatabaseHelper(AndreinartisticaContext context)
        {
            _context = context;
        }
```

2024-11-11 05:39 UTC, Juancaceres963 commented
I still can't get the fetch to work properly with Topics.

2024-11-14 14:52 UTC, merged