Create maxprice API
Juancaceres963/ReactApp.Net pull request #15
Opened 2024-11-20 15:22 UTC by Juancaceres963

2024-11-21 21:46 UTC, jaco9419 requested changes

2024-11-21 21:46 UTC, jaco9419 commented on AndreinaArtistica/Helpers/DatabaseHelper.cs
> +        //}
Esto lo puedes borrar

2024-11-21 21:46 UTC, jaco9419 commented on AndreinaArtistica/Resources/MaxPriceResource.cs
> +                new MaxPriceViewModel { Price = (decimal)roundedMaxPrice }
Ya no necesitas el casting a decimal `(decimal)`

2024-11-21 21:46 UTC, jaco9419 commented on AndreinaArtistica/Helpers/Abstract/IDatabaseHelper.cs
> +        //public Task<List<MaxPrice>> GetMaxPriceFromDB();
Esto lo puedes borrar

2024-11-22 16:50 UTC, Juancaceres963 commented on AndreinaArtistica/Helpers/DatabaseHelper.cs
> +        //}
Listo

2024-11-22 16:50 UTC, Juancaceres963 commented on AndreinaArtistica/Resources/MaxPriceResource.cs
> +                new MaxPriceViewModel { Price = (decimal)roundedMaxPrice }
Listo.

2024-11-22 16:50 UTC, Juancaceres963 commented on AndreinaArtistica/Helpers/Abstract/IDatabaseHelper.cs
> +        //public Task<List<MaxPrice>> GetMaxPriceFromDB();
Listo.

2024-11-22 16:50 UTC, merged